project_id = "qlgjfdrhrqfezxjoqjbc"

[functions.chat]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.generate-blog]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false
